import { getSeoUrl } from './seo'

interface OgImageParams {
  type?: 'default' | 'blog' | 'docs' | 'changelog'
  slug?: string
  title?: string
  description?: string
  date?: string
  author?: string
  tags?: string[]
}

/**
 * Resolve the og:image URL for a page. The base is environment-aware via
 * `getSeoUrl` (localhost in dev, convomem.com in prod):
 *
 * - Production: points at the prerendered static PNG (`/og/<type>/<slug>.png`)
 *   generated by `scripts/generate-og.ts` — zero runtime cost, no font fetch.
 * - Development: points at the runtime `/api/og` route so the image previews
 *   live without a build.
 */
export function getOgImageUrl(params: OgImageParams = {}): string {
  const isContent = params.type && params.type !== 'default' && params.slug

  if (import.meta.env.PROD && isContent) {
    return getSeoUrl(`/og/${params.type}/${params.slug}.png`)
  }

  const query = new URLSearchParams()
  if (params.type && params.type !== 'default') query.set('type', params.type)
  if (params.title) query.set('title', params.title)
  if (params.description) query.set('description', params.description)
  if (params.date) query.set('date', params.date)
  if (params.author) query.set('author', params.author)
  if (params.tags && params.tags.length > 0) {
    query.set('tags', params.tags.join(','))
  }

  const qs = query.toString()
  return getSeoUrl(qs ? `/api/og?${qs}` : '/api/og')
}
