// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteCustomersByIdData, DeleteCustomersByIdErrors, DeleteCustomersByIdMemoriesByMemIdData, DeleteCustomersByIdMemoriesByMemIdErrors, DeleteCustomersByIdMemoriesByMemIdResponses, DeleteCustomersByIdResponses, GetCustomersByIdConversationsData, GetCustomersByIdConversationsErrors, GetCustomersByIdConversationsResponses, GetCustomersByIdData, GetCustomersByIdErrors, GetCustomersByIdMemoriesData, GetCustomersByIdMemoriesErrors, GetCustomersByIdMemoriesLookupData, GetCustomersByIdMemoriesLookupErrors, GetCustomersByIdMemoriesLookupResponses, GetCustomersByIdMemoriesResponses, GetCustomersByIdResponses, GetCustomersData, GetCustomersErrors, GetCustomersLookupData, GetCustomersLookupErrors, GetCustomersLookupResponses, GetCustomersMemoriesLookupData, GetCustomersMemoriesLookupErrors, GetCustomersMemoriesLookupResponses, GetCustomersResponses, PatchCustomersByIdConversationsByCidData, PatchCustomersByIdConversationsByCidErrors, PatchCustomersByIdConversationsByCidEscalateData, PatchCustomersByIdConversationsByCidEscalateErrors, PatchCustomersByIdConversationsByCidEscalateResponses, PatchCustomersByIdConversationsByCidResponses, PatchCustomersByIdData, PatchCustomersByIdErrors, PatchCustomersByIdMemoriesByMemIdData, PatchCustomersByIdMemoriesByMemIdErrors, PatchCustomersByIdMemoriesByMemIdResponses, PatchCustomersByIdResponses, PostCaptureData, PostCaptureErrors, PostCaptureResponses, PostCustomersByIdConversationsData, PostCustomersByIdConversationsErrors, PostCustomersByIdConversationsResponses, PostCustomersByIdMemoriesIngestData, PostCustomersByIdMemoriesIngestErrors, PostCustomersByIdMemoriesIngestResponses, PostCustomersConversationsEndData, PostCustomersConversationsEndErrors, PostCustomersConversationsEndResponses, PostCustomersConversationsEscalateData, PostCustomersConversationsEscalateErrors, PostCustomersConversationsEscalateResponses, PostCustomersData, PostCustomersErrors, PostCustomersResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Capture a message and auto-manage session
 *
 * Single endpoint for external integrators. Resolves customer identity, finds or creates an active conversation session, enqueues the message for memory extraction, and returns the session context. No explicit start/end lifecycle calls required. Accepts either a single message string or a full messages array (with user + assistant turns) — one is required.
 *
 */
export const postCapture = <ThrowOnError extends boolean = false>(options: Options<PostCaptureData, ThrowOnError>) => (options.client ?? client).post<PostCaptureResponses, PostCaptureErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/capture',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Lookup customer by identifier with optional semantic memory
 *
 * Find a customer by internal UUID, phone number, email address, or external ID. At least one identity parameter must be provided.
 *
 * **topic** — When provided, returns semantically relevant memories ranked by vector similarity instead of the 10 most recent. Also returns a pre-formatted `context` string ready to inject into an LLM prompt and a `tokenCount` estimate.
 *
 * **autoCreate** — When `true`, automatically creates a new customer record if the identifier is not found. The response will include `isNewCustomer: true`. Use `userName` to set the display name for newly created customers.
 *
 * This is the primary "plug-and-forget" endpoint for bot integrations. A single call resolves identity, creates new customers, and returns relevant memory context — no internal IDs required.
 *
 */
export const getCustomersLookup = <ThrowOnError extends boolean = false>(options?: Options<GetCustomersLookupData, ThrowOnError>) => (options?.client ?? client).get<GetCustomersLookupResponses, GetCustomersLookupErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/lookup',
    ...options
});

/**
 * List customers
 *
 * Retrieve a paginated list of customers for the organization.
 */
export const getCustomers = <ThrowOnError extends boolean = false>(options?: Options<GetCustomersData, ThrowOnError>) => (options?.client ?? client).get<GetCustomersResponses, GetCustomersErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers',
    ...options
});

/**
 * Create a new customer
 *
 * Create a customer profile for an organization. At least one of email, phone, or externalId must be provided.
 *
 */
export const postCustomers = <ThrowOnError extends boolean = false>(options: Options<PostCustomersData, ThrowOnError>) => (options.client ?? client).post<PostCustomersResponses, PostCustomersErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a customer
 *
 * Permanently delete a customer and all associated data.
 */
export const deleteCustomersById = <ThrowOnError extends boolean = false>(options: Options<DeleteCustomersByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteCustomersByIdResponses, DeleteCustomersByIdErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}',
    ...options
});

/**
 * Get a single customer
 *
 * Retrieve full details for a specific customer by ID.
 */
export const getCustomersById = <ThrowOnError extends boolean = false>(options: Options<GetCustomersByIdData, ThrowOnError>) => (options.client ?? client).get<GetCustomersByIdResponses, GetCustomersByIdErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}',
    ...options
});

/**
 * Update a customer
 *
 * Update one or more fields on an existing customer.
 */
export const patchCustomersById = <ThrowOnError extends boolean = false>(options: Options<PatchCustomersByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchCustomersByIdResponses, PatchCustomersByIdErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * End a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid} but accepts customerId and conversationId in the request body. Designed for bot platforms that don't support dynamic path parameters or PATCH method.
 *
 */
export const postCustomersConversationsEnd = <ThrowOnError extends boolean = false>(options: Options<PostCustomersConversationsEndData, ThrowOnError>) => (options.client ?? client).post<PostCustomersConversationsEndResponses, PostCustomersConversationsEndErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/conversations/end',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Escalate a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid}/escalate but accepts customerId and conversationId in the request body.
 *
 */
export const postCustomersConversationsEscalate = <ThrowOnError extends boolean = false>(options: Options<PostCustomersConversationsEscalateData, ThrowOnError>) => (options.client ?? client).post<PostCustomersConversationsEscalateResponses, PostCustomersConversationsEscalateErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/conversations/escalate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ingest a completed conversation for memory extraction
 *
 * Batch import endpoint — enqueue a completed conversation (full message history including both user and assistant turns) for asynchronous memory extraction. Use this for historical imports, CRM sync, or post-processing third-party transcripts. For real-time capture use POST /api/v1/capture instead.
 *
 */
export const postCustomersByIdMemoriesIngest = <ThrowOnError extends boolean = false>(options: Options<PostCustomersByIdMemoriesIngestData, ThrowOnError>) => (options.client ?? client).post<PostCustomersByIdMemoriesIngestResponses, PostCustomersByIdMemoriesIngestErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/memories/ingest',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Look up relevant memories for a topic
 *
 * Retrieve contextually relevant memories for a given topic, formatted and ready to inject into an LLM prompt. Uses vector similarity search combined with importance and recency scoring.
 *
 */
export const getCustomersByIdMemoriesLookup = <ThrowOnError extends boolean = false>(options: Options<GetCustomersByIdMemoriesLookupData, ThrowOnError>) => (options.client ?? client).get<GetCustomersByIdMemoriesLookupResponses, GetCustomersByIdMemoriesLookupErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/memories/lookup',
    ...options
});

/**
 * Look up relevant memories by identity (no UUID needed)
 *
 * Retrieve contextually relevant memories for a topic using phone, email, or external ID to identify the customer — no internal UUID required. Useful for bot integrations that only have a phone number or email.
 *
 */
export const getCustomersMemoriesLookup = <ThrowOnError extends boolean = false>(options: Options<GetCustomersMemoriesLookupData, ThrowOnError>) => (options.client ?? client).get<GetCustomersMemoriesLookupResponses, GetCustomersMemoriesLookupErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/memories/lookup',
    ...options
});

/**
 * List customer memories
 *
 * Retrieve a paginated list of stored memories for a customer.
 */
export const getCustomersByIdMemories = <ThrowOnError extends boolean = false>(options: Options<GetCustomersByIdMemoriesData, ThrowOnError>) => (options.client ?? client).get<GetCustomersByIdMemoriesResponses, GetCustomersByIdMemoriesErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/memories',
    ...options
});

/**
 * Delete a customer memory
 *
 * Permanently remove a specific memory entry.
 */
export const deleteCustomersByIdMemoriesByMemId = <ThrowOnError extends boolean = false>(options: Options<DeleteCustomersByIdMemoriesByMemIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteCustomersByIdMemoriesByMemIdResponses, DeleteCustomersByIdMemoriesByMemIdErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/memories/{memId}',
    ...options
});

/**
 * Update a customer memory
 *
 * Update fields on an existing memory entry.
 */
export const patchCustomersByIdMemoriesByMemId = <ThrowOnError extends boolean = false>(options: Options<PatchCustomersByIdMemoriesByMemIdData, ThrowOnError>) => (options.client ?? client).patch<PatchCustomersByIdMemoriesByMemIdResponses, PatchCustomersByIdMemoriesByMemIdErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/memories/{memId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List conversations
 *
 * Retrieve a paginated list of conversations for a customer.
 */
export const getCustomersByIdConversations = <ThrowOnError extends boolean = false>(options: Options<GetCustomersByIdConversationsData, ThrowOnError>) => (options.client ?? client).get<GetCustomersByIdConversationsResponses, GetCustomersByIdConversationsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/conversations',
    ...options
});

/**
 * Start a conversation
 *
 * Begin a new conversation session for a customer.
 */
export const postCustomersByIdConversations = <ThrowOnError extends boolean = false>(options: Options<PostCustomersByIdConversationsData, ThrowOnError>) => (options.client ?? client).post<PostCustomersByIdConversationsResponses, PostCustomersByIdConversationsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * End a conversation
 *
 * Mark a conversation as completed with an optional outcome note.
 */
export const patchCustomersByIdConversationsByCid = <ThrowOnError extends boolean = false>(options: Options<PatchCustomersByIdConversationsByCidData, ThrowOnError>) => (options.client ?? client).patch<PatchCustomersByIdConversationsByCidResponses, PatchCustomersByIdConversationsByCidErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/conversations/{cid}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Escalate a conversation
 *
 * Mark a conversation as escalated, optionally providing a reason.
 */
export const patchCustomersByIdConversationsByCidEscalate = <ThrowOnError extends boolean = false>(options: Options<PatchCustomersByIdConversationsByCidEscalateData, ThrowOnError>) => (options.client ?? client).patch<PatchCustomersByIdConversationsByCidEscalateResponses, PatchCustomersByIdConversationsByCidEscalateErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/customers/{id}/conversations/{cid}/escalate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
