// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.convomem.com/api/v1' | (string & {});
};

export type MemoryContext = {
    /**
     * Formatted context string ready for LLM injection
     */
    context?: string;
    /**
     * Estimated token count of the context
     */
    tokenCount?: number;
    memories?: Array<{
        id?: string;
        content?: string;
        category?: string;
        memoryType?: string;
        relevance?: number;
        sentiment?: string | null;
        sourceContext?: string | null;
    }>;
};

export type PostCaptureData = {
    /**
     * Either `message` or `messages` is required. At least one identity field (`customerId`, `externalId`, `email`, or `phoneNumber`) is required.
     *
     */
    body: {
        /**
         * Single user message (simple form). Required if messages not provided.
         */
        message?: string;
        /**
         * Full conversation turns including assistant replies. Required if message not provided.
         */
        messages?: Array<{
            role: 'user' | 'assistant' | 'system';
            content: string;
        }>;
        /**
         * Identity field — at least one of customerId, externalId, email, or phoneNumber is required.
         */
        customerId?: string;
        /**
         * Identity field — at least one of customerId, externalId, email, or phoneNumber is required.
         */
        externalId?: string;
        /**
         * Identity field — at least one of customerId, externalId, email, or phoneNumber is required.
         */
        email?: string;
        /**
         * Identity field — at least one of customerId, externalId, email, or phoneNumber is required.
         */
        phoneNumber?: string;
        /**
         * Customer display name — used to set or update the customer profile name (backfills placeholder names like phone numbers)
         */
        userName?: string;
        channel?: 'VOICE' | 'CHAT' | 'SMS' | 'EMAIL';
        idempotencyKey?: string;
    };
    path?: never;
    query?: never;
    url: '/capture';
};

export type PostCaptureErrors = {
    /**
     * Validation error
     */
    422: unknown;
};

export type PostCaptureResponses = {
    /**
     * Message appended to existing conversation
     */
    200: {
        conversationId?: string;
        customerId?: string;
        status?: 'new' | 'active';
        isNewConversation?: boolean;
        isNewCustomer?: boolean;
    };
    /**
     * New conversation created
     */
    201: {
        /**
         * The conversation session ID (reused across calls for the same customer while session is active)
         */
        conversationId?: string;
        /**
         * The resolved or newly created customer ID
         */
        customerId?: string;
        /**
         * 'new' if a new conversation was started, 'active' if appended to an existing session
         */
        status?: 'new' | 'active';
        /**
         * true when this call started a new conversation session
         */
        isNewConversation?: boolean;
        /**
         * true when the customer was created by this call
         */
        isNewCustomer?: boolean;
    };
};

export type PostCaptureResponse = PostCaptureResponses[keyof PostCaptureResponses];

export type GetCustomersLookupData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path?: never;
    query?: {
        /**
         * Internal customer UUID
         */
        customerId?: string;
        /**
         * Customer phone number
         */
        phone?: string;
        /**
         * Customer email address
         */
        email?: string;
        /**
         * External system identifier
         */
        externalId?: string;
        /**
         * Topic or customer message to find relevant memories for. When provided, memories are ranked by semantic relevance and a pre-formatted context string is returned.
         *
         */
        topic?: string;
        /**
         * Auto-create customer if not found. Response includes isNewCustomer flag.
         *
         */
        autoCreate?: 'true' | 'false';
        /**
         * Display name for auto-created customers
         */
        userName?: string;
    };
    url: '/customers/lookup';
};

export type GetCustomersLookupErrors = {
    /**
     * Missing or invalid query parameter
     */
    400: unknown;
    /**
     * Unauthorized — invalid or missing credentials
     */
    401: unknown;
};

export type GetCustomersLookupResponses = {
    /**
     * Lookup result with optional semantic memories
     */
    200: {
        found?: boolean;
        /**
         * true when customer was auto-created by this call
         */
        isNewCustomer?: boolean;
        customer?: {
            id?: string;
            name?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            metadata?: {
                [key: string]: unknown;
            };
            createdAt?: string;
        } | null;
        /**
         * Recent or topic-relevant memories
         */
        memories?: Array<{
            id?: string;
            /**
             * The memory fact text
             */
            content?: string;
            /**
             * Memory category (e.g. preference, customer_profile, purchase_history, pain_point)
             */
            category?: string;
            /**
             * Type of memory (fact, preference, intent, goal)
             */
            memoryType?: string;
            /**
             * Semantic similarity score (0-1) — only present when topic is provided
             */
            relevance?: number;
            /**
             * Detected sentiment (positive, negative, neutral, null)
             */
            sentiment?: string | null;
            /**
             * Original conversation snippet the memory was extracted from
             */
            sourceContext?: string | null;
        }>;
        /**
         * Pre-formatted context string for LLM injection (only when topic is provided)
         */
        context?: string | null;
        /**
         * Estimated token count of context string (only when topic is provided)
         */
        tokenCount?: number;
    };
};

export type GetCustomersLookupResponse = GetCustomersLookupResponses[keyof GetCustomersLookupResponses];

export type GetCustomersData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/customers';
};

export type GetCustomersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetCustomersResponses = {
    /**
     * Paginated list of customers
     */
    200: {
        data?: Array<{
            id?: string;
            name?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            createdAt?: string;
        }>;
        page?: number;
        limit?: number;
        total?: number;
    };
};

export type GetCustomersResponse = GetCustomersResponses[keyof GetCustomersResponses];

export type PostCustomersData = {
    body: {
        /**
         * Customer display name
         */
        name?: string;
        /**
         * Customer email address
         */
        email?: string;
        /**
         * Customer phone number
         */
        phone?: string;
        /**
         * External system identifier
         */
        externalId?: string;
        /**
         * Arbitrary key-value metadata
         */
        metadata?: {
            [key: string]: unknown;
        };
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path?: never;
    query?: never;
    url: '/customers';
};

export type PostCustomersErrors = {
    /**
     * Validation error — at least one identifier required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer with this identifier already exists
     */
    409: unknown;
};

export type PostCustomersResponses = {
    /**
     * Customer created successfully
     */
    201: {
        id?: string;
        name?: string;
        email?: string;
        phone?: string;
        externalId?: string;
        metadata?: {
            [key: string]: unknown;
        };
        createdAt?: string;
    };
};

export type PostCustomersResponse = PostCustomersResponses[keyof PostCustomersResponses];

export type DeleteCustomersByIdData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type DeleteCustomersByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type DeleteCustomersByIdResponses = {
    /**
     * Customer deleted successfully
     */
    200: unknown;
};

export type GetCustomersByIdData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type GetCustomersByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type GetCustomersByIdResponses = {
    /**
     * Customer details
     */
    200: {
        id?: string;
        name?: string;
        email?: string;
        phone?: string;
        externalId?: string;
        metadata?: {
            [key: string]: unknown;
        };
        createdAt?: string;
        updatedAt?: string;
    };
};

export type GetCustomersByIdResponse = GetCustomersByIdResponses[keyof GetCustomersByIdResponses];

export type PatchCustomersByIdData = {
    body: {
        name?: string;
        email?: string;
        phone?: string;
        externalId?: string;
        metadata?: {
            [key: string]: unknown;
        };
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type PatchCustomersByIdErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
    /**
     * Conflict — identifier already in use by another customer
     */
    409: unknown;
};

export type PatchCustomersByIdResponses = {
    /**
     * Customer updated successfully
     */
    200: {
        id?: string;
        name?: string;
        email?: string;
        phone?: string;
        externalId?: string;
        metadata?: {
            [key: string]: unknown;
        };
        updatedAt?: string;
    };
};

export type PatchCustomersByIdResponse = PatchCustomersByIdResponses[keyof PatchCustomersByIdResponses];

export type PostCustomersConversationsEndData = {
    body: {
        customerId: string;
        conversationId: string;
        outcome?: string;
    };
    path?: never;
    query?: never;
    url: '/customers/conversations/end';
};

export type PostCustomersConversationsEndErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Customer or conversation not found
     */
    404: unknown;
};

export type PostCustomersConversationsEndResponses = {
    /**
     * Conversation ended
     */
    200: unknown;
};

export type PostCustomersConversationsEscalateData = {
    body: {
        customerId: string;
        conversationId: string;
        reason?: string;
    };
    path?: never;
    query?: never;
    url: '/customers/conversations/escalate';
};

export type PostCustomersConversationsEscalateErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Customer or conversation not found
     */
    404: unknown;
};

export type PostCustomersConversationsEscalateResponses = {
    /**
     * Conversation escalated
     */
    200: unknown;
};

export type PostCustomersByIdMemoriesIngestData = {
    body: {
        messages: Array<{
            role: 'user' | 'assistant';
            content: string;
        }>;
        channel?: 'VOICE' | 'CHAT' | 'SMS' | 'EMAIL';
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}/memories/ingest';
};

export type PostCustomersByIdMemoriesIngestErrors = {
    /**
     * Validation error — messages array required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type PostCustomersByIdMemoriesIngestResponses = {
    /**
     * Capture request accepted and queued
     */
    202: {
        captureId?: string;
        status?: 'queued';
    };
};

export type PostCustomersByIdMemoriesIngestResponse = PostCustomersByIdMemoriesIngestResponses[keyof PostCustomersByIdMemoriesIngestResponses];

export type GetCustomersByIdMemoriesLookupData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query: {
        /**
         * The topic or query to find relevant memories for
         */
        topic: string;
    };
    url: '/customers/{id}/memories/lookup';
};

export type GetCustomersByIdMemoriesLookupErrors = {
    /**
     * Missing topic query parameter
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type GetCustomersByIdMemoriesLookupResponses = {
    /**
     * Relevant memories formatted for LLM injection
     */
    200: {
        /**
         * Pre-formatted context string for LLM prompt injection
         */
        context?: string;
        memories?: Array<{
            id?: string;
            fact?: string;
            category?: string;
            importance?: number;
            score?: number;
        }>;
        /**
         * Total token count of the context string
         */
        tokenCount?: number;
    };
};

export type GetCustomersByIdMemoriesLookupResponse = GetCustomersByIdMemoriesLookupResponses[keyof GetCustomersByIdMemoriesLookupResponses];

export type GetCustomersMemoriesLookupData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path?: never;
    query: {
        /**
         * The topic or query to find relevant memories for
         */
        topic: string;
        /**
         * Customer phone number (one of phone/email/externalId required)
         */
        phone?: string;
        /**
         * Customer email address (one of phone/email/externalId required)
         */
        email?: string;
        /**
         * External system identifier (one of phone/email/externalId required)
         */
        externalId?: string;
    };
    url: '/customers/memories/lookup';
};

export type GetCustomersMemoriesLookupErrors = {
    /**
     * Missing topic or identity params
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type GetCustomersMemoriesLookupResponses = {
    /**
     * Relevant memories formatted for LLM injection
     */
    200: MemoryContext;
};

export type GetCustomersMemoriesLookupResponse = GetCustomersMemoriesLookupResponses[keyof GetCustomersMemoriesLookupResponses];

export type GetCustomersByIdMemoriesData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/customers/{id}/memories';
};

export type GetCustomersByIdMemoriesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type GetCustomersByIdMemoriesResponses = {
    /**
     * Paginated list of memories
     */
    200: {
        data?: Array<{
            id?: string;
            fact?: string;
            category?: string;
            importance?: number;
            createdAt?: string;
        }>;
        page?: number;
        limit?: number;
        total?: number;
    };
};

export type GetCustomersByIdMemoriesResponse = GetCustomersByIdMemoriesResponses[keyof GetCustomersByIdMemoriesResponses];

export type DeleteCustomersByIdMemoriesByMemIdData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
        /**
         * Memory ID
         */
        memId: string;
    };
    query?: never;
    url: '/customers/{id}/memories/{memId}';
};

export type DeleteCustomersByIdMemoriesByMemIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer or memory not found
     */
    404: unknown;
};

export type DeleteCustomersByIdMemoriesByMemIdResponses = {
    /**
     * Memory deleted successfully
     */
    200: unknown;
};

export type PatchCustomersByIdMemoriesByMemIdData = {
    body: {
        fact?: string;
        category?: string;
        importance?: number;
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
        /**
         * Memory ID
         */
        memId: string;
    };
    query?: never;
    url: '/customers/{id}/memories/{memId}';
};

export type PatchCustomersByIdMemoriesByMemIdErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer or memory not found
     */
    404: unknown;
};

export type PatchCustomersByIdMemoriesByMemIdResponses = {
    /**
     * Memory updated successfully
     */
    200: unknown;
};

export type GetCustomersByIdConversationsData = {
    body?: never;
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/customers/{id}/conversations';
};

export type GetCustomersByIdConversationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type GetCustomersByIdConversationsResponses = {
    /**
     * Paginated list of conversations
     */
    200: {
        data?: Array<{
            id?: string;
            channel?: string;
            status?: string;
            startedAt?: string;
            endedAt?: string | null;
        }>;
        page?: number;
        limit?: number;
        total?: number;
    };
};

export type GetCustomersByIdConversationsResponse = GetCustomersByIdConversationsResponses[keyof GetCustomersByIdConversationsResponses];

export type PostCustomersByIdConversationsData = {
    body: {
        channel: 'VOICE' | 'CHAT' | 'SMS' | 'EMAIL';
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}/conversations';
};

export type PostCustomersByIdConversationsErrors = {
    /**
     * Validation error — channel is required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer not found
     */
    404: unknown;
};

export type PostCustomersByIdConversationsResponses = {
    /**
     * Conversation started
     */
    201: {
        id?: string;
        customerId?: string;
        channel?: 'VOICE' | 'CHAT' | 'SMS' | 'EMAIL';
        status?: 'ACTIVE';
    };
};

export type PostCustomersByIdConversationsResponse = PostCustomersByIdConversationsResponses[keyof PostCustomersByIdConversationsResponses];

export type PatchCustomersByIdConversationsByCidData = {
    body?: {
        /**
         * Summary of conversation outcome
         */
        outcome?: string;
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
        /**
         * Conversation ID
         */
        cid: string;
    };
    query?: never;
    url: '/customers/{id}/conversations/{cid}';
};

export type PatchCustomersByIdConversationsByCidErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer or conversation not found
     */
    404: unknown;
};

export type PatchCustomersByIdConversationsByCidResponses = {
    /**
     * Conversation ended
     */
    200: {
        id?: string;
        status?: 'COMPLETED';
        endedAt?: string;
    };
};

export type PatchCustomersByIdConversationsByCidResponse = PatchCustomersByIdConversationsByCidResponses[keyof PatchCustomersByIdConversationsByCidResponses];

export type PatchCustomersByIdConversationsByCidEscalateData = {
    body?: {
        /**
         * Reason for escalation
         */
        reason?: string;
    };
    headers?: {
        /**
         * Organization ID (required with Bearer auth)
         */
        'X-Org-Id'?: string;
    };
    path: {
        /**
         * Customer ID
         */
        id: string;
        /**
         * Conversation ID
         */
        cid: string;
    };
    query?: never;
    url: '/customers/{id}/conversations/{cid}/escalate';
};

export type PatchCustomersByIdConversationsByCidEscalateErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Customer or conversation not found
     */
    404: unknown;
};

export type PatchCustomersByIdConversationsByCidEscalateResponses = {
    /**
     * Conversation escalated
     */
    200: {
        id?: string;
        status?: 'ESCALATED';
    };
};

export type PatchCustomersByIdConversationsByCidEscalateResponse = PatchCustomersByIdConversationsByCidEscalateResponses[keyof PatchCustomersByIdConversationsByCidEscalateResponses];
