// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, useMutation, type UseMutationOptions, useQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteCustomersById, deleteCustomersByIdMemoriesByMemId, getCustomers, getCustomersById, getCustomersByIdConversations, getCustomersByIdMemories, getCustomersByIdMemoriesLookup, getCustomersLookup, getCustomersMemoriesLookup, type Options, patchCustomersById, patchCustomersByIdConversationsByCid, patchCustomersByIdConversationsByCidEscalate, patchCustomersByIdMemoriesByMemId, postCapture, postCustomers, postCustomersByIdConversations, postCustomersByIdMemoriesIngest, postCustomersConversationsEnd, postCustomersConversationsEscalate } from '../sdk.gen';
import type { DeleteCustomersByIdData, DeleteCustomersByIdMemoriesByMemIdData, GetCustomersByIdConversationsData, GetCustomersByIdConversationsResponse, GetCustomersByIdData, GetCustomersByIdMemoriesData, GetCustomersByIdMemoriesLookupData, GetCustomersByIdMemoriesLookupResponse, GetCustomersByIdMemoriesResponse, GetCustomersByIdResponse, GetCustomersData, GetCustomersLookupData, GetCustomersLookupResponse, GetCustomersMemoriesLookupData, GetCustomersMemoriesLookupResponse, GetCustomersResponse, PatchCustomersByIdConversationsByCidData, PatchCustomersByIdConversationsByCidEscalateData, PatchCustomersByIdConversationsByCidEscalateResponse, PatchCustomersByIdConversationsByCidResponse, PatchCustomersByIdData, PatchCustomersByIdMemoriesByMemIdData, PatchCustomersByIdResponse, PostCaptureData, PostCaptureResponse, PostCustomersByIdConversationsData, PostCustomersByIdConversationsResponse, PostCustomersByIdMemoriesIngestData, PostCustomersByIdMemoriesIngestResponse, PostCustomersConversationsEndData, PostCustomersConversationsEscalateData, PostCustomersData, PostCustomersResponse } from '../types.gen';

/**
 * Capture a message and auto-manage session
 *
 * Single endpoint for external integrators. Resolves customer identity, finds or creates an active conversation session, enqueues the message for memory extraction, and returns the session context. No explicit start/end lifecycle calls required. Accepts either a single message string or a full messages array (with user + assistant turns) — one is required.
 *
 */
export const postCaptureMutation = (options?: Partial<Options<PostCaptureData>>): UseMutationOptions<PostCaptureResponse, DefaultError, Options<PostCaptureData>> => {
    const mutationOptions: UseMutationOptions<PostCaptureResponse, DefaultError, Options<PostCaptureData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCapture({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Capture a message and auto-manage session
 *
 * Single endpoint for external integrators. Resolves customer identity, finds or creates an active conversation session, enqueues the message for memory extraction, and returns the session context. No explicit start/end lifecycle calls required. Accepts either a single message string or a full messages array (with user + assistant turns) — one is required.
 *
 */
export const usePostCaptureMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PostCaptureResponse, DefaultError, Options<PostCaptureData>>, 'mutationFn'>>) => useMutation({ ...postCaptureMutation(), ...mutationOptions });

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCustomersLookupQueryKey = (options?: Options<GetCustomersLookupData>) => createQueryKey('getCustomersLookup', options);

/**
 * Lookup customer by identifier with optional semantic memory
 *
 * Find a customer by internal UUID, phone number, email address, or external ID. At least one identity parameter must be provided.
 *
 * **topic** — When provided, returns semantically relevant memories ranked by vector similarity instead of the 10 most recent. Also returns a pre-formatted `context` string ready to inject into an LLM prompt and a `tokenCount` estimate.
 *
 * **autoCreate** — When `true`, automatically creates a new customer record if the identifier is not found. The response will include `isNewCustomer: true`. Use `userName` to set the display name for newly created customers.
 *
 * This is the primary "plug-and-forget" endpoint for bot integrations. A single call resolves identity, creates new customers, and returns relevant memory context — no internal IDs required.
 *
 */
export const getCustomersLookupOptions = (options?: Options<GetCustomersLookupData>) => queryOptions<GetCustomersLookupResponse, DefaultError, GetCustomersLookupResponse, ReturnType<typeof getCustomersLookupQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersLookup({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersLookupQueryKey(options)
});

/**
 * Lookup customer by identifier with optional semantic memory
 *
 * Find a customer by internal UUID, phone number, email address, or external ID. At least one identity parameter must be provided.
 *
 * **topic** — When provided, returns semantically relevant memories ranked by vector similarity instead of the 10 most recent. Also returns a pre-formatted `context` string ready to inject into an LLM prompt and a `tokenCount` estimate.
 *
 * **autoCreate** — When `true`, automatically creates a new customer record if the identifier is not found. The response will include `isNewCustomer: true`. Use `userName` to set the display name for newly created customers.
 *
 * This is the primary "plug-and-forget" endpoint for bot integrations. A single call resolves identity, creates new customers, and returns relevant memory context — no internal IDs required.
 *
 */
export const useGetCustomersLookupQuery = (options?: Options<GetCustomersLookupData>) => useQuery(getCustomersLookupOptions(options));

export const getCustomersQueryKey = (options?: Options<GetCustomersData>) => createQueryKey('getCustomers', options);

/**
 * List customers
 *
 * Retrieve a paginated list of customers for the organization.
 */
export const getCustomersOptions = (options?: Options<GetCustomersData>) => queryOptions<GetCustomersResponse, DefaultError, GetCustomersResponse, ReturnType<typeof getCustomersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getCustomersInfiniteQueryKey = (options?: Options<GetCustomersData>): QueryKey<Options<GetCustomersData>> => createQueryKey('getCustomers', options, true);

/**
 * List customers
 *
 * Retrieve a paginated list of customers for the organization.
 */
export const getCustomersInfiniteOptions = (options?: Options<GetCustomersData>) => infiniteQueryOptions<GetCustomersResponse, DefaultError, InfiniteData<GetCustomersResponse>, QueryKey<Options<GetCustomersData>>, number | Pick<QueryKey<Options<GetCustomersData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCustomersData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCustomers({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersInfiniteQueryKey(options)
});

/**
 * List customers
 *
 * Retrieve a paginated list of customers for the organization.
 */
export const useGetCustomersQuery = (options?: Options<GetCustomersData>) => useQuery(getCustomersOptions(options));

/**
 * Create a new customer
 *
 * Create a customer profile for an organization. At least one of email, phone, or externalId must be provided.
 *
 */
export const postCustomersMutation = (options?: Partial<Options<PostCustomersData>>): UseMutationOptions<PostCustomersResponse, DefaultError, Options<PostCustomersData>> => {
    const mutationOptions: UseMutationOptions<PostCustomersResponse, DefaultError, Options<PostCustomersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCustomers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a new customer
 *
 * Create a customer profile for an organization. At least one of email, phone, or externalId must be provided.
 *
 */
export const usePostCustomersMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PostCustomersResponse, DefaultError, Options<PostCustomersData>>, 'mutationFn'>>) => useMutation({ ...postCustomersMutation(), ...mutationOptions });

/**
 * Delete a customer
 *
 * Permanently delete a customer and all associated data.
 */
export const deleteCustomersByIdMutation = (options?: Partial<Options<DeleteCustomersByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCustomersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a customer
 *
 * Permanently delete a customer and all associated data.
 */
export const useDeleteCustomersByIdMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdData>>, 'mutationFn'>>) => useMutation({ ...deleteCustomersByIdMutation(), ...mutationOptions });

export const getCustomersByIdQueryKey = (options: Options<GetCustomersByIdData>) => createQueryKey('getCustomersById', options);

/**
 * Get a single customer
 *
 * Retrieve full details for a specific customer by ID.
 */
export const getCustomersByIdOptions = (options: Options<GetCustomersByIdData>) => queryOptions<GetCustomersByIdResponse, DefaultError, GetCustomersByIdResponse, ReturnType<typeof getCustomersByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdQueryKey(options)
});

/**
 * Get a single customer
 *
 * Retrieve full details for a specific customer by ID.
 */
export const useGetCustomersByIdQuery = (options: Options<GetCustomersByIdData>) => useQuery(getCustomersByIdOptions(options));

/**
 * Update a customer
 *
 * Update one or more fields on an existing customer.
 */
export const patchCustomersByIdMutation = (options?: Partial<Options<PatchCustomersByIdData>>): UseMutationOptions<PatchCustomersByIdResponse, DefaultError, Options<PatchCustomersByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchCustomersByIdResponse, DefaultError, Options<PatchCustomersByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchCustomersById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a customer
 *
 * Update one or more fields on an existing customer.
 */
export const usePatchCustomersByIdMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PatchCustomersByIdResponse, DefaultError, Options<PatchCustomersByIdData>>, 'mutationFn'>>) => useMutation({ ...patchCustomersByIdMutation(), ...mutationOptions });

/**
 * End a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid} but accepts customerId and conversationId in the request body. Designed for bot platforms that don't support dynamic path parameters or PATCH method.
 *
 */
export const postCustomersConversationsEndMutation = (options?: Partial<Options<PostCustomersConversationsEndData>>): UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEndData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEndData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCustomersConversationsEnd({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * End a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid} but accepts customerId and conversationId in the request body. Designed for bot platforms that don't support dynamic path parameters or PATCH method.
 *
 */
export const usePostCustomersConversationsEndMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEndData>>, 'mutationFn'>>) => useMutation({ ...postCustomersConversationsEndMutation(), ...mutationOptions });

/**
 * Escalate a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid}/escalate but accepts customerId and conversationId in the request body.
 *
 */
export const postCustomersConversationsEscalateMutation = (options?: Partial<Options<PostCustomersConversationsEscalateData>>): UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEscalateData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEscalateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCustomersConversationsEscalate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Escalate a conversation (flat — no path params)
 *
 * Same as PATCH /customers/{id}/conversations/{cid}/escalate but accepts customerId and conversationId in the request body.
 *
 */
export const usePostCustomersConversationsEscalateMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, DefaultError, Options<PostCustomersConversationsEscalateData>>, 'mutationFn'>>) => useMutation({ ...postCustomersConversationsEscalateMutation(), ...mutationOptions });

/**
 * Ingest a completed conversation for memory extraction
 *
 * Batch import endpoint — enqueue a completed conversation (full message history including both user and assistant turns) for asynchronous memory extraction. Use this for historical imports, CRM sync, or post-processing third-party transcripts. For real-time capture use POST /api/v1/capture instead.
 *
 */
export const postCustomersByIdMemoriesIngestMutation = (options?: Partial<Options<PostCustomersByIdMemoriesIngestData>>): UseMutationOptions<PostCustomersByIdMemoriesIngestResponse, DefaultError, Options<PostCustomersByIdMemoriesIngestData>> => {
    const mutationOptions: UseMutationOptions<PostCustomersByIdMemoriesIngestResponse, DefaultError, Options<PostCustomersByIdMemoriesIngestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCustomersByIdMemoriesIngest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Ingest a completed conversation for memory extraction
 *
 * Batch import endpoint — enqueue a completed conversation (full message history including both user and assistant turns) for asynchronous memory extraction. Use this for historical imports, CRM sync, or post-processing third-party transcripts. For real-time capture use POST /api/v1/capture instead.
 *
 */
export const usePostCustomersByIdMemoriesIngestMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PostCustomersByIdMemoriesIngestResponse, DefaultError, Options<PostCustomersByIdMemoriesIngestData>>, 'mutationFn'>>) => useMutation({ ...postCustomersByIdMemoriesIngestMutation(), ...mutationOptions });

export const getCustomersByIdMemoriesLookupQueryKey = (options: Options<GetCustomersByIdMemoriesLookupData>) => createQueryKey('getCustomersByIdMemoriesLookup', options);

/**
 * Look up relevant memories for a topic
 *
 * Retrieve contextually relevant memories for a given topic, formatted and ready to inject into an LLM prompt. Uses vector similarity search combined with importance and recency scoring.
 *
 */
export const getCustomersByIdMemoriesLookupOptions = (options: Options<GetCustomersByIdMemoriesLookupData>) => queryOptions<GetCustomersByIdMemoriesLookupResponse, DefaultError, GetCustomersByIdMemoriesLookupResponse, ReturnType<typeof getCustomersByIdMemoriesLookupQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersByIdMemoriesLookup({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdMemoriesLookupQueryKey(options)
});

/**
 * Look up relevant memories for a topic
 *
 * Retrieve contextually relevant memories for a given topic, formatted and ready to inject into an LLM prompt. Uses vector similarity search combined with importance and recency scoring.
 *
 */
export const useGetCustomersByIdMemoriesLookupQuery = (options: Options<GetCustomersByIdMemoriesLookupData>) => useQuery(getCustomersByIdMemoriesLookupOptions(options));

export const getCustomersMemoriesLookupQueryKey = (options: Options<GetCustomersMemoriesLookupData>) => createQueryKey('getCustomersMemoriesLookup', options);

/**
 * Look up relevant memories by identity (no UUID needed)
 *
 * Retrieve contextually relevant memories for a topic using phone, email, or external ID to identify the customer — no internal UUID required. Useful for bot integrations that only have a phone number or email.
 *
 */
export const getCustomersMemoriesLookupOptions = (options: Options<GetCustomersMemoriesLookupData>) => queryOptions<GetCustomersMemoriesLookupResponse, DefaultError, GetCustomersMemoriesLookupResponse, ReturnType<typeof getCustomersMemoriesLookupQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersMemoriesLookup({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersMemoriesLookupQueryKey(options)
});

/**
 * Look up relevant memories by identity (no UUID needed)
 *
 * Retrieve contextually relevant memories for a topic using phone, email, or external ID to identify the customer — no internal UUID required. Useful for bot integrations that only have a phone number or email.
 *
 */
export const useGetCustomersMemoriesLookupQuery = (options: Options<GetCustomersMemoriesLookupData>) => useQuery(getCustomersMemoriesLookupOptions(options));

export const getCustomersByIdMemoriesQueryKey = (options: Options<GetCustomersByIdMemoriesData>) => createQueryKey('getCustomersByIdMemories', options);

/**
 * List customer memories
 *
 * Retrieve a paginated list of stored memories for a customer.
 */
export const getCustomersByIdMemoriesOptions = (options: Options<GetCustomersByIdMemoriesData>) => queryOptions<GetCustomersByIdMemoriesResponse, DefaultError, GetCustomersByIdMemoriesResponse, ReturnType<typeof getCustomersByIdMemoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersByIdMemories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdMemoriesQueryKey(options)
});

export const getCustomersByIdMemoriesInfiniteQueryKey = (options: Options<GetCustomersByIdMemoriesData>): QueryKey<Options<GetCustomersByIdMemoriesData>> => createQueryKey('getCustomersByIdMemories', options, true);

/**
 * List customer memories
 *
 * Retrieve a paginated list of stored memories for a customer.
 */
export const getCustomersByIdMemoriesInfiniteOptions = (options: Options<GetCustomersByIdMemoriesData>) => infiniteQueryOptions<GetCustomersByIdMemoriesResponse, DefaultError, InfiniteData<GetCustomersByIdMemoriesResponse>, QueryKey<Options<GetCustomersByIdMemoriesData>>, number | Pick<QueryKey<Options<GetCustomersByIdMemoriesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCustomersByIdMemoriesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCustomersByIdMemories({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdMemoriesInfiniteQueryKey(options)
});

/**
 * List customer memories
 *
 * Retrieve a paginated list of stored memories for a customer.
 */
export const useGetCustomersByIdMemoriesQuery = (options: Options<GetCustomersByIdMemoriesData>) => useQuery(getCustomersByIdMemoriesOptions(options));

/**
 * Delete a customer memory
 *
 * Permanently remove a specific memory entry.
 */
export const deleteCustomersByIdMemoriesByMemIdMutation = (options?: Partial<Options<DeleteCustomersByIdMemoriesByMemIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdMemoriesByMemIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdMemoriesByMemIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCustomersByIdMemoriesByMemId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a customer memory
 *
 * Permanently remove a specific memory entry.
 */
export const useDeleteCustomersByIdMemoriesByMemIdMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, DefaultError, Options<DeleteCustomersByIdMemoriesByMemIdData>>, 'mutationFn'>>) => useMutation({ ...deleteCustomersByIdMemoriesByMemIdMutation(), ...mutationOptions });

/**
 * Update a customer memory
 *
 * Update fields on an existing memory entry.
 */
export const patchCustomersByIdMemoriesByMemIdMutation = (options?: Partial<Options<PatchCustomersByIdMemoriesByMemIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchCustomersByIdMemoriesByMemIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchCustomersByIdMemoriesByMemIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchCustomersByIdMemoriesByMemId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a customer memory
 *
 * Update fields on an existing memory entry.
 */
export const usePatchCustomersByIdMemoriesByMemIdMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<unknown, DefaultError, Options<PatchCustomersByIdMemoriesByMemIdData>>, 'mutationFn'>>) => useMutation({ ...patchCustomersByIdMemoriesByMemIdMutation(), ...mutationOptions });

export const getCustomersByIdConversationsQueryKey = (options: Options<GetCustomersByIdConversationsData>) => createQueryKey('getCustomersByIdConversations', options);

/**
 * List conversations
 *
 * Retrieve a paginated list of conversations for a customer.
 */
export const getCustomersByIdConversationsOptions = (options: Options<GetCustomersByIdConversationsData>) => queryOptions<GetCustomersByIdConversationsResponse, DefaultError, GetCustomersByIdConversationsResponse, ReturnType<typeof getCustomersByIdConversationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCustomersByIdConversations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdConversationsQueryKey(options)
});

export const getCustomersByIdConversationsInfiniteQueryKey = (options: Options<GetCustomersByIdConversationsData>): QueryKey<Options<GetCustomersByIdConversationsData>> => createQueryKey('getCustomersByIdConversations', options, true);

/**
 * List conversations
 *
 * Retrieve a paginated list of conversations for a customer.
 */
export const getCustomersByIdConversationsInfiniteOptions = (options: Options<GetCustomersByIdConversationsData>) => infiniteQueryOptions<GetCustomersByIdConversationsResponse, DefaultError, InfiniteData<GetCustomersByIdConversationsResponse>, QueryKey<Options<GetCustomersByIdConversationsData>>, number | Pick<QueryKey<Options<GetCustomersByIdConversationsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCustomersByIdConversationsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCustomersByIdConversations({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCustomersByIdConversationsInfiniteQueryKey(options)
});

/**
 * List conversations
 *
 * Retrieve a paginated list of conversations for a customer.
 */
export const useGetCustomersByIdConversationsQuery = (options: Options<GetCustomersByIdConversationsData>) => useQuery(getCustomersByIdConversationsOptions(options));

/**
 * Start a conversation
 *
 * Begin a new conversation session for a customer.
 */
export const postCustomersByIdConversationsMutation = (options?: Partial<Options<PostCustomersByIdConversationsData>>): UseMutationOptions<PostCustomersByIdConversationsResponse, DefaultError, Options<PostCustomersByIdConversationsData>> => {
    const mutationOptions: UseMutationOptions<PostCustomersByIdConversationsResponse, DefaultError, Options<PostCustomersByIdConversationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCustomersByIdConversations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Start a conversation
 *
 * Begin a new conversation session for a customer.
 */
export const usePostCustomersByIdConversationsMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PostCustomersByIdConversationsResponse, DefaultError, Options<PostCustomersByIdConversationsData>>, 'mutationFn'>>) => useMutation({ ...postCustomersByIdConversationsMutation(), ...mutationOptions });

/**
 * End a conversation
 *
 * Mark a conversation as completed with an optional outcome note.
 */
export const patchCustomersByIdConversationsByCidMutation = (options?: Partial<Options<PatchCustomersByIdConversationsByCidData>>): UseMutationOptions<PatchCustomersByIdConversationsByCidResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidData>> => {
    const mutationOptions: UseMutationOptions<PatchCustomersByIdConversationsByCidResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchCustomersByIdConversationsByCid({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * End a conversation
 *
 * Mark a conversation as completed with an optional outcome note.
 */
export const usePatchCustomersByIdConversationsByCidMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PatchCustomersByIdConversationsByCidResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidData>>, 'mutationFn'>>) => useMutation({ ...patchCustomersByIdConversationsByCidMutation(), ...mutationOptions });

/**
 * Escalate a conversation
 *
 * Mark a conversation as escalated, optionally providing a reason.
 */
export const patchCustomersByIdConversationsByCidEscalateMutation = (options?: Partial<Options<PatchCustomersByIdConversationsByCidEscalateData>>): UseMutationOptions<PatchCustomersByIdConversationsByCidEscalateResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidEscalateData>> => {
    const mutationOptions: UseMutationOptions<PatchCustomersByIdConversationsByCidEscalateResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidEscalateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchCustomersByIdConversationsByCidEscalate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Escalate a conversation
 *
 * Mark a conversation as escalated, optionally providing a reason.
 */
export const usePatchCustomersByIdConversationsByCidEscalateMutation = (mutationOptions?: Partial<Omit<UseMutationOptions<PatchCustomersByIdConversationsByCidEscalateResponse, DefaultError, Options<PatchCustomersByIdConversationsByCidEscalateData>>, 'mutationFn'>>) => useMutation({ ...patchCustomersByIdConversationsByCidEscalateMutation(), ...mutationOptions });
